#!/bin/sh

# remove previously generated Autotools output
files_to_remove=" \
    config.h \
	aclocal.m4 \
	autom4te.cache \
	config.h.in \
	configure \
	config/depcomp \
	config/install-sh \
	config/ltmain.sh \
	config/missing \
	config/py-compile \
	config/m4/libtool.m4 \
	config/m4/lt~obsolete.m4 \
	config/m4/ltoptions.m4 \
	config/m4/ltsugar.m4 \
	config/m4/ltversion.m4 \
	`find . -name 'Makefile.in'`"
rm -rf $files_to_remove

# check for libtoolize command
libtoolize_cmd="$LIBTOOLIZE"
if [ -z "$libtoolize_cmd" ] ; then
	which libtoolize >/dev/null 2>&1
	if [ "$?" = 0 ] ; then
		libtoolize_cmd="libtoolize"
	else
		which glibtoolize >/dev/null 2>&1
		if [ "$?" = 0 ] ; then
			libtoolize_cmd="glibtoolize"
		else
			echo "$0: error: neither \"libtoolize\" nor \"glibtoolize\" found"
			exit 1
		fi
	fi
fi

# run GNU autotools
$libtoolize_cmd --automake --copy
aclocal -I config/m4
autoheader
autoconf
automake --add-missing --copy --include-deps

